* Owen Barfield:Romanticism Come of Age
  :PROPERTIES:
  :CUSTOM_ID: owen-barfieldromanticism-come-of-age
  :END:

** Simon Blaxland-de Lange
   :PROPERTIES:
   :CUSTOM_ID: simon-blaxland-de-lange
   :END:

Temple Lodge Publishing Hillside House, The Square Forest Row, RH18 5ES

2006

Foreward Andrew Welbourn

The clash is especially clear in cases where Barfield sought to get at the reality of such myths as ancient Atlantis. He came to believe that the key to understanding that reality lay in the 'changing consciousness', as he liked to put it, of humanity over ages of historical time. The universality of the myths pointed to their basis in a kind of world-experience that was different from our own, but appealed deeply to our minds because it formed the very basis from which ours had evolved. Using his insight into the history of language, Barfield argued that abstract ideas were a late development in the way people thought about the world. But that did not mean that early humanity lived in an impoverished, confused, merely sensory landscape. Quite the contrary.

It is modern human beings who feel cut off from their environment, who see it passing by them in an unintelligible, alienated way, merely registered on their senses but without deeper significance. Early humanity felt part of the world they knew, and felt every aspect of it---colour, sound, form---to be charged with profound meaning. The history of language showed that human beings were deeply aware of the paradoxes and questions of human existence, but they expressed them in myths, symbols, 'concrete' forms of thought, and ultimately in a consciousness of the world which we can still comprehend, at least in some measure, in its otherness to our own. pp. x-xi
